# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
  - repo: https://github.com/TekWizely/pre-commit-golang
    rev: v1.0.0-beta.5
    hooks:
      - id: go-fmt
        args: [ -w ]
      #- id: my-cmd-mod
      #  name: swag-fmt
      #  alias: swag-fmt
      #  args: [ swag, fmt ]
      - id: go-mod-tidy
      - id: golangci-lint-mod
      #- id: go-sec-mod
      - id: go-vet-mod
#      - id: go-test-mod
  - repo: https://github.com/hadolint/hadolint
    rev: v2.10.0
    hooks:
      - id: hadolint
        args: [--ignore, DL3018]
